site_name: usrbin.app Docs
site_url: https://usrbin.app
theme:
  name: material
  features:
    - navigation.instant
  icon:
    repo: fontawesome/brands/github
pages:
  - index.md
  - concepts.md
  - why-update.md
  - security.md
  - updaters.md
  - package-managers.md
  - install.md
  - sdks/go.md
  - roadmap.md
markdown_extensions:
  - admonition
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/usrbinapp/userbin-docs
edit_uri: edit/main/docs
