site_name: usrbin.app Docs
site_url: https://www-usrbin-app.marccampbell.workers.dev/docs/
theme:
  name: material
  features:
    - navigation.instant
  icon:
    repo: fontawesome/brands/github
pages:
  - index.md
markdown_extensions:
  - admonition
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/usrbinapp/userbin-docs
edit_uri: edit/main/docs
